# Python CircleCI 2.0 configuration file
# vi: et:ts=2:sw=2
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4.9-jessie
    working_directory: ~/python-mbedtls
    steps:
      - checkout
      - run:
          name: install pyenv
          command: |
            git clone https://github.com/pyenv/pyenv.git $HOME/python-mbedtls/.pyenv
            cat << 'EOF' >> $BASH_ENV
            export PYENV_ROOT="$HOME/python-mbedtls/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            EOF

      - restore_cache:
          keys:
            - py27-v2-{{ arch }}-2.7.15
      - run:
          name: install python 2.7
          command: |
            if [ ! -d ".pyenv/versions/2.7.15" ]; then
              eval "$(pyenv init -)"
              pyenv install 2.7.15
            fi
      - save_cache:
          key: py27-v2-{{ arch }}-2.7.15
          paths:
            - .pyenv/versions/2.7.15

      - restore_cache:
          keys:
            - py34-v2-{{ arch }}-3.4.9
      - run:
          name: install python 3.4
          command: |
            if [ ! -d ".pyenv/versions/3.4.9" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.4.9
            fi
      - save_cache:
          key: py34-v2-{{ arch }}-3.4.9
          paths:
            - .pyenv/versions/3.4.9

      - restore_cache:
          keys:
            - py35-v2-{{ arch }}-3.5.6
      - run:
          name: install python 3.5
          command: |
            if [ ! -d ".pyenv/versions/3.5.6" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.5.6
            fi
      - save_cache:
          key: py35-v2-{{ arch }}-3.5.6
          paths:
            - .pyenv/versions/3.5.6

      - restore_cache:
          keys:
            - py36-v2-{{ arch }}-3.6.6
      - run:
          name: install python 3.6
          command: |
            if [ ! -d ".pyenv/versions/3.6.6" ]; then
              eval "$(pyenv init -)"
              pyenv install 3.6.6
            fi
      - save_cache:
          key: py36-v2-{{ arch }}-3.6.6
          paths:
            - .pyenv/versions/3.6.6

      - run:
          name: install mbedtls
          command: |
            VERSION=2.14.1
            DESTDIR=$HOME/lib/$VERSION
            sudo apt-get install cmake
            sudo ./scripts/install-mbedtls.sh $VERSION $DESTDIR
            cat << EOF >> $BASH_ENV
            export VERSION=$VERSION
            export DESTDIR=$DESTDIR
            export LD_LIBRARY_PATH=$DESTDIR/lib
            export C_INCLUDE_PATH=$DESTDIR/include
            EOF

      - run:
          name: Create environment
          command: python -m venv venv

      - run:
          name: run tests
          command: |
            eval "$(pyenv init -)"
            pyenv shell 2.7.15 3.4.9 3.5.6 3.6.6
            . venv/bin/activate
            pip install tox
            tox -p auto -e py27,py34,py35,py36
            tox -e py36-doctest

      - run:
          name: save logs
          command: |
            mkdir -p out/log
            cp .tox/*/log/py*.log out/log || true
          when: on_fail

      - store_artifacts:
          path: out
          destination: artifacts
